spring.application.name=bsol-backend
# Spring Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/pgsoldb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Storage Configuration
#local or gcp
storage.type=local
storage.local.path=./uploads
storage.gcp.bucket-name=bsol-room-images
storage.gcp.project-id=bsol-project
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
#Actuator
management.endpoints.web.exposure.include=health
# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
openapi.bachelorSolution.base-path=/uv-api/v1
openapi.bachelorSolutionMaster.base-path=/uv-api/v1

# Gmail SMTP — 16-char app password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaibhavzalte1004@gmail.com
spring.mail.password=wepmqwfhsmmfpwwvvvvy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# OTP configuration
app.otp.expiry-minutes=5
app.otp.length=6

app.admin.name=Vaibhav
app.admin.email=vaibhavzalte1004@gmail.com
app.admin.password=1234